### ISSUE TITLE
failed to synchronize: cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by fxcdl** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#6]
Hi, thanks for your code
When I use the GPU to train for a while, i got this error. 
Is it my pytorch version problem?(cuda113, pytorch1.12.1)
![22acdde16474ec363bc58db2e40b47b](https://user-images.githubusercontent.com/50817018/205677021-a88e34e5-6fab-4a17-8919-a19724b709a2.png)

**Comment by ma-xu** [comment]
@fxcdl Looks like I never met this problem. My environment is: cuda/11.0 gcc/8.1.0 torch/1.9.0.

**Comment by fxcdl** [comment]
I solved this problem by setting device to cuda:1
